// Startup code modified from https://github.com/haydenridd/stm32-baremetal-zig/blob/main/src/startup.zig
extern fn SystemInit() callconv(.c) void;
extern fn __libc_init_array() callconv(.c) void;
extern fn main() callconv(.c) noreturn;

comptime {
    @export(&resetHandler, .{
        .name = "resetHandler",
        .linkage = .strong,
    });
}
comptime {
    @export(&__start, .{
        .name = "__start",
        .linkage = .strong,
    });
}

extern const _estack: anyopaque;

pub fn resetHandler() callconv(.naked) noreturn {

    //The instruction `ldr sp, =_estack` is redundant (done by hardware) but can be useful when we soft reset to ensure stack pointer to be reset.
    //We use naked attribute to not get prologue/epilogue, then we continue with __start function.
    asm volatile (
        \\ ldr sp, =_estack
        \\ b   __start
        ::: .{ .memory = true });
}

// Original function found in the startup_stm32f407xx.s assembly file. Generated by STM32CubeMX.
pub fn __start() callconv(.c) noreturn {
    const startup_locations = struct {
        extern var _sbss: u8;
        extern var _ebss: u8;
        extern var _sdata: u8;
        extern var _edata: u8;
        extern const _sidata: u8;
    };

    // Setup the microcontroller system, Initialize the FPU setting, vector table location and External memory configuration
    SystemInit();

    // fill .bss with zeroes
    {
        const bss_start: [*]u8 = @ptrCast(&startup_locations._sbss);
        const bss_end: [*]u8 = @ptrCast(&startup_locations._ebss);
        const bss_len = @intFromPtr(bss_end) - @intFromPtr(bss_start);

        @memset(bss_start[0..bss_len], 0);
    }

    // load .data from flash
    {
        const data_start: [*]u8 = @ptrCast(&startup_locations._sdata);
        const data_end: [*]u8 = @ptrCast(&startup_locations._edata);
        const data_len = @intFromPtr(data_end) - @intFromPtr(data_start);
        const data_src: [*]const u8 = @ptrCast(&startup_locations._sidata);

        @memcpy(data_start[0..data_len], data_src[0..data_len]);
    }

    // Call static constructors (newlib)
    __libc_init_array();

    main();
}
