const std = @import("std");
const c = @import("translate.zig"); // Generated by cmake in this folder
const b58 = @import("base58.zig");

pub const Error = error{
    InputNoData,
    BufferEmpty,
};

//export the cmake project name hashed.
comptime {
    @export(&hash_project_name, .{
        .name = "hash_project_name",
        .linkage = .strong,
    });
}
const hash_project_name: u32 = std.hash.CityHash32.hash(c.PROJECT_NAME);

fn error_to_c(err: anyerror) c_int {
    return -@as(c_int, @intFromError(err));
}

export fn zig_error_to_string(err: c_int) callconv(.c) *const c_char {
    if (err < 0) {
        const u_err: u16 = @intCast(-err);
        //The next line is not safe if the error id don't exist.
        const string: *const c_char = @ptrCast(@errorName(@errorFromInt(u_err)));
        return string;
    }
    return @ptrCast("Not an error code");
}

export fn b58_encode(input: ?[*]const u8, inlen: usize, buffer: ?[*]u8, outlen: usize) callconv(.c) c_int {
    const in_opt = if (input) |val| val[0..inlen] else return error_to_c(Error.InputNoData);
    const buffer_opt = if (buffer) |val| val[0..outlen] else return error_to_c(Error.BufferEmpty);

    _ = b58.encode(in_opt, buffer_opt) catch |err| {
        return error_to_c(err);
    };
    return 0;
}

export fn b58_decode(input: ?[*]const u8, inlen: usize, buffer: ?[*]u8, outlen: usize) callconv(.c) c_int {
    const in_opt = if (input) |val| val[0..inlen] else return error_to_c(Error.InputNoData);
    const buffer_opt = if (buffer) |val| val[0..outlen] else return error_to_c(Error.BufferEmpty);

    _ = b58.decode(in_opt, buffer_opt) catch |err| {
        return error_to_c(err);
    };
    return 0;
}

export fn cityhash64(input: ?[*]const u8, len: usize) callconv(.c) u64 {
    if (input) |input_opt| {
        return std.hash.CityHash64.hash(input_opt[0..len]);
    } else {
        return 0;
    }
}
