FROM fedora:43
LABEL description "Build Picolibc" \
    maintainer="Sazerac4 <lm-embeddedsystems@laposte.net>"

#Install tools
RUN yum install --setopt=install_weak_deps=False -y git unzip meson ninja-build llvm clang lld \
    && yum clean all && rm -rf -- /var/cache/yum

#Download picolibc
ARG PICOLIBC_VERSION="1.8.11"
RUN curl -L -o picolibc.zip https://github.com/picolibc/picolibc/archive/refs/tags/${PICOLIBC_VERSION}.zip \
    && unzip picolibc.zip && mv picolibc-${PICOLIBC_VERSION} /picolibc \
    && rm picolibc.zip

WORKDIR /workspace
VOLUME /workspace

CMD [ "/bin/bash" ]
