name: ci workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GCC_VERSION: "15.2.rel1"
  ZIG_VERSION: "0.15.2"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache ARM GCC
        uses: actions/cache@v4
        id: cache-gcc
        with:
          path: |
            /opt/tools/xpack-arm-none-eabi-gcc-${{ env.GCC_VERSION }}
            /usr/local/bin/arm-none-eabi-*
          key: ${{ runner.os }}-arm-gcc-${{ env.GCC_VERSION }}

      - name: Cache Zig
        uses: actions/cache@v4
        id: cache-zig
        with:
          path: |
            /opt/tools/zig-x86_64-linux-${{ env.ZIG_VERSION }}
            /usr/local/bin/zig
          key: ${{ runner.os }}-zig-${{ env.ZIG_VERSION }}

      - name: Install ARM GCC
        if: steps.cache-gcc.outputs.cache-hit != 'true'
        run: |
          mkdir -vp /opt/tools/gcc-arm-none-eabi
          curl -L -o gcc-arm-none-eabi.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/${GCC_VERSION}/binrel/arm-gnu-toolchain-${GCC_VERSION}-x86_64-arm-none-eabi.tar.xz
          tar xf gcc-arm-none-eabi.tar.xz -C /opt/tools/gcc-arm-none-eabi
          ln -s /opt/tools/gcc-arm-none-eabi/bin/* /usr/local/bin/
          rm gcc-arm-none-eabi.tar.xz

      - name: Install Zig
        if: steps.cache-zig.outputs.cache-hit != 'true'
        run: |
          mkdir -vp /opt/tools
          curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz
          tar -xf zig.tar.xz -C /opt/tools/
          ln -s /opt/tools/zig-x86_64-linux-*/zig /usr/local/bin/
          rm zig.tar.xz

      - name: Build examples
        run: sh ci/build-examples.sh
